pull_request_rules:
  - name: automatic merge for bot pull requests on master
    conditions:
      - author=renovate[bot]
      - author=imgbot[bot]
      - author=renovate
      - author=imgbot
      - base=master
    actions:
      merge:
        method: merge
