pull_request_rules:
  - name: automatic merge for bot pull requests on master
    conditions:
      - author=renovate[bot]
      - author=imgbot[bot]
      - author=renovate-bot
      - author=imgbot-bot
      - base=master
    actions:
      merge:
        method: merge
